### ISSUE TITLE
Re-organize init command to be the combination of other commands

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#109]
Right now we tend to duplicate logic between project init, env add and init. As we add app init, this problem will probably get worse. Instead should just call the EnvAddOpts.Ask/Execute, and ProjectInitOpts.Ask/Execute commands.

**Comment by efekarakus** [comment]
I'll pick up the piece for `app init` it's becoming a mess now

**Comment by efekarakus** [comment]
Prerequisites to achieve this:
- [ ] Parity between `archer env init` and `archer init`
- [ ] Parity between `archer project init` and `archer init`
Currently these commands are missing flags that're part of `archer init`.

Rough programming model:
```
# in init.go

# log intro blurb
initProject.Ask()
initProject.Validate()
initProject.Execute()

# transition blurb to app
initApp.Ask()
initApp.Validate()
initApp.Execute()

# transition blurb to env
initEnv.Ask()
initEnv.Validate()
initEnv.Execute()
```

**Comment by efekarakus** [comment]
This is done for `app init` and `project init`, we need to do the same for the environment!  

We can pick this back up when we have to touch that part of the code base but it's already half as short :)
