### ISSUE TITLE
Project show

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#11]
`ecs project show`

This command should:
1. Detect which project the working directory is associated with via the Project.yml files in ecs/*Project.yml (if run in a working directory, otherwise it should prompt for the name of the project)

2. Show The environments associated with this project and the applications associated with this project.

**Comment by efekarakus** [comment]
Implemented in https://github.com/aws/amazon-ecs-cli-v2/pull/588
