### ISSUE TITLE
`env add` tries to add to non-existent project

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#117]
In a clean directory, with no projects named `BadGoose`, `archer env add` attempts to add an environment to a project named `BadGoose`.

```
~/ecs/ecs-devx/testing/archer$ ls -a
.	..

~/ecs/ecs-devx/testing/archer$ tree -a
.

0 directories, 0 files

~/ecs/ecs-devx/testing/archer$ archer project ls
12334

~/ecs/ecs-devx/testing/archer$ archer env add
? What is your environment's name? foo
Error: couldn't find a project named BadGoose in account xxxxxxxxxxxx and region us-west-2

```

**Comment by kohidave** [comment]
I think the best thing to do for this is to do a best effort guess at if we're in a Git workspace, and pin the workspace root at the same level as the .git dir.

**Comment by efekarakus** [comment]
We renamed the directory to `ecs-project/` which should reduce the occurrences of this problem. I think sufficient time has passed without being surprised by this issue. I'll resolve this and create a new one if a customer complains.
