### ISSUE TITLE
Need intro to terminology

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli-v2#126]
We need intros / docs around the application vs project terminology.  Would be especially helpful in archer init wizard, where I'm using the tool for the first time.

i.e. no idea on first run what the difference is between these two:
```
$ archer init
? What is your project's name? archerm1bugbash
? What is your application's name? [? for help]
```

**Comment by kohidave** [comment]
I think we do a better job of this now! Lemme know if you think we should be more explicit, but otherwise I'll close this :)
