### ISSUE TITLE
Deploy application command

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#13]
`ecs deploy`

This command will:
0. Prompt the user to select which environment to deploy to (or accept it as a CLI param)
1. Build the current application's Dockerfile
2. Register it with ECR (Have we not created this yet?) 
3. Build the Manifest to CloudFormation
4. Execute a CloudFormation update with the manifest's CF and ECR image

**Comment by SoManyHs** [comment]
As per discussion the other day, we may want to coordinate with the Pipeline application command as well.
