### ISSUE TITLE
Can't create new project after running archer init once

### ISSUE THREAD

**Issue by bvtujo** [aws/amazon-ecs-cli-v2#130]
I'm a new user exploring archer and running `archer init`. I've run it once in a test directory, but I realized that I mistyped my project name. I want to create a new one, so I delete my test directory and run `archer init` in a fresh dir. 

### Expected:
I can start again by specifying a new project name.

### Actual: 
I see the following output:
```bash
? Which project should we use? [Use arrows to move, type to filter, ? for more help]
> MyAwfulService
```
and cannot understand how to make a new project!

**Comment by kohidave** [comment]
We've fixed this up now. We ask if you'd like to create a new project in init.
