### ISSUE TITLE
Bug Bash Feedback: More descriptive errors

### ISSUE THREAD

**Issue by pkandasamy91** [aws/amazon-ecs-cli-v2#131]
Thanks for bug bashing archer! Feel free to leave feedback for a bug, usability issue or just general feedback. Let us know the command you ran and the OS you're running on. Screen shots are super useful, too.

186590cd8c21:test piradeep$ archer init
? What is your project's name? DavidLovesPonies
? What is your application's name? TinyPonies
? Which template would you like to use? Load Balanced Web App
Error: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: b6a816ed-b826-4b8b-907f-4b6a9658ae6f

My Isengard credentials expired, this exception could be more descriptive.

**Comment by efekarakus** [comment]
We added verbose logging in case of session errors hopefully this should provide more info to debug: 

https://github.com/aws/amazon-ecs-cli-v2/blob/84f02ce9cda4c80b57bdca2cbd4e724969332f54/internal/pkg/aws/session/session.go#L101
