### ISSUE TITLE
Guidance needed on where to run archer init

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli-v2#132]
For first-time users, how should we provide guidance on what directory to run archer init in?  I started out running it in my Downloads directory, which isn't a particularly useful place to put an ecs/ directory.  Should we look for a .git directory in the current working directory, and confirm intent if we don't find it?

**Comment by kohidave** [comment]
👍 That's a great idea.

**Comment by clareliguori** [comment]
I noticed this error `Note: It's best to run this command in the root of your workspace.`

I find "workspace" a confusing term, if we really mean inside a git repository.  I thought it meant my home directory :)

**Comment by efekarakus** [comment]
@clareliguori https://github.com/aws/amazon-ecs-cli-v2/pull/468

**Comment by efekarakus** [comment]
Fixed in https://github.com/aws/amazon-ecs-cli-v2/pull/468
