### ISSUE TITLE
Bug Bash Feedback: archer init - Inconsistent Behaviour

### ISSUE THREAD

**Issue by pkandasamy91** [aws/amazon-ecs-cli-v2#133]
archer init
? What is your project's name? DavidLovesPonies
? What is your application's name? TinyPonies
? Which template would you like to use? Load Balanced Web App
Error: UnrecognizedClientException: The security token included in the request is invalid.
	status code: 400, request id: b6a816ed-b826-4b8b-907f-4b6a9658ae6f

If an exception happens on the init call, the Project name is saved, but the Application name is not. I would expect both Project and Application name to both either be saved or removed.

**Comment by kohidave** [comment]
While there are still times when we can make partial progress, we make sure we can deploy to the account before we write the project state.

**Comment by efekarakus** [comment]
This UX has changed significantly with `project init` spinning up a stack for infrastructure roles. I'll resolve this issue.
