### ISSUE TITLE
Bug Bash Feedback: archer init freezes when typing a new name

### ISSUE THREAD

**Issue by PettitWesley** [aws/amazon-ecs-cli-v2#134]
```
$ archer init
? Which project should we use?  [Use arrows to move, type to filter, ? for more help]
> woohoo
```

When I type a new project name, ex "test", the old name, "woohoo" is overwritten. However, when I press enter to select the new name, the terminal just freezes and nothing happens.

**Comment by kohidave** [comment]
We ask if you want to create a project, now :D
