### ISSUE TITLE
[archer init] Flags somewhat confusingly specified as required in help menu

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#137]
```
~/ecs/ecs-devx/testing/archer$ archer init --help
Create a new ECS application

Usage
  archer init [flags]

Flags
  -a, --app string       Name of the application (required).
  -h, --help             help for init
  -p, --project string   Name of the project (required).
      --skip-deploy      Skips asking if you want to do a deployment.
  -t, --type string      Type of application to create.
```

To me, this suggests that the `--app` and `--project` flags are required, even though you can specify them interactively. Perhaps clarify in the description in the command?

**Comment by efekarakus** [comment]
We changed this! We don't write `"(required)"` anymore if a flag is needed to execute the command. Instead, flags that are optional have a description prefixed with `"Optional. {text}"`
