### ISSUE TITLE
Fail to init the application because "index out of range [-1]"

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#138]
<img width="1199" alt="Screen Shot 2019-09-30 at 3 39 27 PM" src="https://user-images.githubusercontent.com/51377557/65922057-e8190a00-e398-11e9-8372-b5320792f6d7.png">

So if I manually input the "Load Balanced Web App" then I add an extra space like "Load Balanced Web App " then I input the arrows like "up down left right" some random combination by my keyboard. Then I hit "Enter" then delete the trailing space and hit "Enter". The error shows up. I know I might be the only weird user doing this but it is a bug...

**Comment by efekarakus** [comment]
@iamhopaul123 do you know if this still happens? I feel like this is unusual enough that we can close.

**Comment by iamhopaul123** [comment]
Yeah. This is a very bad user input :)
