### ISSUE TITLE
Bug Bash Feedback: flickering "<spinner> Deploying env..."

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#140]
After running `archer init`
? What is your project's name? k
? What is your application's name? ap
? Which template would you like to use? Load Balanced Web App
? Would you like to set up a test environment? Yes
⠴ Deploying env...

while the `Deploying env...` is spinning, occasionally I noticed the entire line flickers as Archer redraws it.

**Comment by kohidave** [comment]
Closing this - since we mostly use Efe's super cool new spinner.
