### ISSUE TITLE
Bug Bash Feedback: archer init unable to create two projects

### ISSUE THREAD

**Issue by pkandasamy91** [aws/amazon-ecs-cli-v2#143]
186590cd8c21:Downloads piradeep$ mkdir test2
186590cd8c21:Downloads piradeep$ cd test2
186590cd8c21:test2 piradeep$ archer init
? What is your application's name? BobsYourUncle
? Which template would you like to use? Load Balanced Web App
Error: failed to marshal the manifest file stat /Users/piradeep/Downloads/test2/template/load-balanced-fargate-service.yml: no such file or directory

My Downloads directory contains a test1 and test2 directory. test1 contained a project DavidLovesPonies, when i do an archer init in test2, I expect to be able to create a new project but it still refers to DavidLovesPonies, and only the ecs directory exists within test2.

**Comment by kohidave** [comment]
Ok, we've revamped the init experience so I'll close this for now. It doesn't stop this - but it's way more clear what's happening in the new experience.
