### ISSUE TITLE
Bug Bash Feedback: archer init with existing <app name> simply overwrites the app yml file

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#145]
When running `archer init` and provide an app name that already exists like the following:

? What is your application's name? app2
? Which template would you like to use? Load Balanced Web App

Archer overwrites the app yaml file without any warning or confirmation. Not sure this is the behavior we want.

**Comment by efekarakus** [comment]
This behavior won't happen anymore as the CLI errors if the app already exists.

We should probably change that behavior to what you are suggesting to make the commands idempotent. I think that can be captured in a separate issue since it's different than the one listed here.
