### ISSUE TITLE
More than 5 characters in `archer init` filter text starts generating newlines

### ISSUE THREAD

**Issue by bvtujo** [aws/amazon-ecs-cli-v2#146]
I'm starting to make a new project by running `archer init` and I have an existing project. The CLI prompts me to filter existing projects by typing, but when I input more than 5 characters I start to see lots of newlines generated. 
<img width="666" alt="Screen Shot 2019-09-30 at 3 51 24 PM" src="https://user-images.githubusercontent.com/25392995/65922582-9d988d00-e39a-11e9-9e53-a8fd924f606b.png">

**Comment by efekarakus** [comment]
I believe this is the same issue as https://github.com/aws/amazon-ecs-cli-v2/issues/125, resolving this one to track it there.
