### ISSUE TITLE
Bug Bash Feedback: created project although registered to other project

### ISSUE THREAD

**Issue by srrengar** [aws/amazon-ecs-cli-v2#148]
Should error first if the workspace is registered to another project already
![image](https://user-images.githubusercontent.com/30325699/65922629-c7ea4a80-e39a-11e9-8c48-c420931d94b8.png)

**Comment by kohidave** [comment]
`Looks like you are using a workspace that's registered to project dogbones. We'll use that as your project instead of dog.`
