### ISSUE TITLE
Bug Bash Feedback: bubbling CloudFormation error

### ISSUE THREAD

**Issue by uttarasridhar** [aws/amazon-ecs-cli-v2#149]
My environment failed to deploy

```
devhex uttara$ archer env add production --profile archer-test --prod
⠏ Deploying env... Error: ResourceNotReady: failed waiting for successful resource state
```

I had to go step into the cloudformation console to get the error message , only to find out the dreadful error `The maximum number of VPCs has been reached`

**Comment by kohidave** [comment]
This should be much better now!
