### ISSUE TITLE
Clarification needed in terminology between `archer init` and `archer env add`

### ISSUE THREAD

**Issue by bvtujo** [aws/amazon-ecs-cli-v2#152]
As a new user, I'm surprised that `archer init` doesn't necessarily create a cloudformation stack. If I select No when prompted if I would like to set up a test environment, nothing happens. 

This is confusing because when I run `archer env add`, the app creates a cloudformation stack with the name of the new environment. This may overlap with other suggested issues, but some clarification is needed between "Project," "Environment," and "Application" and the roles that they fill in the final service architecture. 

Clarification my also be needed in what precisely "Set up a test environment" means -- will this deploy an environment in the Application I've just defined with `archer init`? Will this deploy a "test" stack alongside my new Application?

**Comment by kohidave** [comment]
Hey hey ! We've updated the init flow with explanations! I'll close this for now :D
