### ISSUE TITLE
Inconsistent experience with archer env add and archer project init

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#153]
```
~/ecs/ecs-devx/testing/archer$ archer env add
? What is your environment's name? 
Error: interrupt

~/ecs/ecs-devx/testing/archer$ archer project init
Error: accepts 1 arg(s), received 0
```

would expect required arguments for a subcommand to be communicated the same way.

Related: https://github.com/aws/PRIVATE-amazon-ecs-archer/issues/123, https://github.com/aws/PRIVATE-amazon-ecs-archer/issues/108

**Comment by kohidave** [comment]
This has been fixed :D
