### ISSUE TITLE
Need "exit" command in `archer init`

### ISSUE THREAD

**Issue by bvtujo** [aws/amazon-ecs-cli-v2#154]
I seem to be locked into creating resources at least locally when I run `archer init` unless I interrupt with Ctrl C. 

If there is no way to abort creating resources from archer init, I may not be aware of changes that are made to my environment if I accidentally run the init command.

**Comment by kohidave** [comment]
With the new first run experience where we ask if you want to deploy, does that help you out?

**Comment by efekarakus** [comment]
We have `delete` commands now to be able to delete individual resources, and soon `project delete` that should take care of these concerns.
