### ISSUE TITLE
Survey validations should include failed string

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#159]
Right now, when we return a validation error in validation.go, we don't include the actual string that failed validation. This can be helpful - see #124 and #118

**Comment by codevbus** [comment]
I'd like to grab this.

**Comment by kohidave** [comment]
Sweet! That'd be awesome @codevbus - feel free to take a crack at it and send a PR. Let me know if you need any help or anything. Really appreciate you taking the time to look at this 🙌!

**Comment by kohidave** [comment]
Hey @codevbus - I know there's been a lot of updates to this project recently - were you still interested in picking this issue up?

**Comment by codevbus** [comment]
@kohidave - for sure! Apologies for dropping this. Real life got in the way a bit. Should have some more ramp time in the coming week to work on this.

**Comment by kohidave** [comment]
No problem at all, and no rush. We're just grateful for your help.

**Comment by efekarakus** [comment]
Looks like we do this now! https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/cli/validate.go#L32

Resolving
