### ISSUE TITLE
archer app init experience

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#172]
I really love the way that the [init](https://github.com/aws/amazon-ecs-cli-v2/issues/158) design exercise resulted. This issue is to try a similar design/discussion around `app init`.

## What is app init?
An application is the core of customer's workflows - it is the actual containerized thing that our customers are trying to deploy along with any specific application specific infrastructure. For example, if our customers are trying to set up an API app, they'll probably want a loadbalancer, an ECS service backed by fargate and a CloudWatch log group. 

## What are application types?

Ok, so how do customers know that they'll need a LoadBalancer, ECS Service, etc. to run their API? Well, rather than make them specify what they need explicitly, they can tell us what *type* of application they're building. For this, we can borrow from the work the CDK did to define ECS Patterns. Our API app that we defined above, for example, could use a LoadBalanced Fargate Service pattern, instead. Now they won't need to worry about getting their application infrastructure "right" but can instead get started with a tried and true application infrastructure pattern.

For the preview launch we'll support the LB Fargate Service application type. 

## Asking the right questions

For `app init`, each application type will have its own set of questions, depending on their needs. All applications will require a type and a name, but after that, it depends on the needs of the application. We should only ask questions for values we can't set reasonable defaults for. 

__in general, this advice applies to the archer init bit of setting up an app, as well__

**Comment by kohidave** [comment]
For the LB Fargate Service, we're trying to get a few pieces of information:

1. Do you already have a Dockerfile you want to use?
2. If so, what is the port that you want to expose to traffic from the Load Balancer?
3. What's the name of this app 

```
archer app init

Let's set up an application. To help you get started, select the type of 
application you'd like to build from our list of application types. 

What type of application do you want to make?
> Load Balanced Web App
``` 
If there are no Dockerfiles in the workspace (that haven't already been assigned to a manifest)
```
It doesn't look like there are any existing Dockerfiles we can use
for a new Load Balanced Web App in your workspace. That's ok,
we'll create one for you.

What do you want to call your Load Balanced Web App? _hello_ 

Ok great, we'll set up a Load Balanced Web App named hello in project Fresh.

Success! Wrote the manifest for hello app at ecs-project/hello-app.yml'
Success! Wrote the Dockerfile for hello app at 'hello/Dockerfile'

Tip: We defaulted to port 80 to send traffic to in your container, but you 
can edit that in your manifest file later, if you'd like.

```
If there are existing Dockerfiles (that haven't already been assigned to a manifest)
```
Would you like to use one of your existing Dockerfiles for your service? [y/n]
```
Yes
```
Sure, which one:
> ./hello/Dockerfile
   ./goodbye/Dockerfile

Which port do you want to send public traffic to on your container? _80_
What do you want to call this Load Balanced Web App? _hello_
Ok great, we'll set up a Load Balanced Web App named hello in project Fresh.

Success! Wrote the manifest for hello app at ecs-project/hello-app.yml'
```
No
```
Go through the empty dockerfile flow above
```

**Comment by kohidave** [comment]
Flags:

```
$ archer app init -h
Create a new ECS application in an existing project. 
This command needs to be run within an  existing ECS workspace.  

Usage
  archer app init [flags]

Flags
  -a, --app string        Name of the application.
  -t, --app-type string   Type of application to create.
  -d  --dockerfile        Location of the Dockerfile to use. 
  -h, --help              help for app init
  --public-port         Container port to forward public traffic to.  
```

**Comment by kohidave** [comment]
@clareliguori @efekarakus @hencrice @sonofachamp

**Comment by efekarakus** [comment]
Looks good!  
1. Should we add a note whenever this command is run like in `init`:  
_Note: It's best to run this command in the root of your workspace._

> If there are no Dockerfiles in the workspace (that haven't already been assigned to a manifest)
2. Instead of searching through existing manifest files, should we search sub-directories for `Dockerfile`s?

> --public-port           Container port to forward public traffic to. 
3. Add (Defaults to 80)? Maybe we shouldn't prompt for this at all and just print the message that they can change it in the manifest whenever they want.

**Comment by clareliguori** [comment]
What would the contents be for the Dockerfile that we create?  Some dummy web server?

**Comment by sonofachamp** [comment]
How is this flow affected when there is no project in context? When there is a project should we assume they want to associate the app with that project, or should we enable attaching this new app to an arbitrary project via a flag?

What if the app isn't a local `Dockerfile` but instead an image in some repository the user wants to deploy? Or is the assumption with this flow always a new application? If that's the case it might be worth considering alternative flows that would support associating some existing application artifact to a project.

**Comment by kohidave** [comment]
> How is this flow affected when there is no project in context? When there is a project should we assume they want to associate the app with that project, or should we enable attaching this new app to an arbitrary project via a flag?
> 
> What if the app isn't a local `Dockerfile` but instead an image in some repository the user wants to deploy? Or is the assumption with this flow always a new application? If that's the case it might be worth considering alternative flows that would support associating some existing application artifact to a project.

Great questions! Let's see.
"How is this flow affected when there is no project in context"

If they aren't in a workspace, I think we can bail with an error.

> You need to be in a workspace to run `app init`. You can also run `archer init` and we'll set up a workspace and project for you. 

"What if the app isn't a local Dockerfile but instead an image in some repository the user wants to deploy"

This is actually really tricky. I'd like to be able to use a raw image, rather than needing a Dockerfile. But, for deploying that image cross region, it becomes trickier. I think for this wizard, we can punt on image support and revisit it later (just because it's a tiny bit more complicated and maybe a bit more advanced). But we should circle back to it at some point.

**Comment by kohidave** [comment]
> Looks good!
> 
>     1. Should we add a note whenever this command is run like in `init`:
>        _Note: It's best to run this command in the root of your workspace._
> 
> 
> > If there are no Dockerfiles in the workspace (that haven't already been assigned to a manifest)
> 
>     1. Instead of searching through existing manifest files, should we search sub-directories for `Dockerfile`s?
> 
> 
> > --public-port           Container port to forward public traffic to.
> 
>     1. Add (Defaults to 80)? Maybe we shouldn't prompt for this at all and just print the message that they can change it in the manifest whenever they want.

I don't think we need to say that it needs to be run in your workspace root until we start creating directories. 

For your second point - I think we should look for Dockerfiles in current + sub directories and exclude those already present in a manifest. 

For the public port, I'm ok leaving it as an info statement - but I suspect most Dockerfiles will expose a non port 80 port.

**Comment by kohidave** [comment]
> What would the contents be for the Dockerfile that we create? Some dummy web server?

Great question. We could use the [ECS Sample app](https://github.com/aws-samples/ecs-demo-php-simple-app/blob/master/Dockerfile), but that's kind of heavy and it's PHP. Maybe something a little more modern or dead simple like http-echo, or flask.

**Comment by kohidave** [comment]
Closing for now. We've got a pretty good app init experience, even though we don't currently create empty repos.
