### ISSUE TITLE
Make project, environment and app names case insensitive

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#185]
Currently, you can create two projects called "interesting-project" and "Interesting-project" which are completely different. 

You can have two environments "test" and "Test" which are also unique envs within a project.

My suspicion is that this will result in customers having some junk in their accounts due to typos. 

GitHub and Beanstalk are case insensitive, as well. Amplify requires lower-case environment names.

ECS Clusters and CloudFormation stacks are case sensitive. 

If we go with the case-insensitive approach, I suggest we store all our records with lowercase letters. 

Thumbs up if you agree 👍, down if you disagree 👎  or shrug 🤷‍♀ if you don't think it matters :P

**Comment by kohidave** [comment]
Sounds good! Let's do it then.

**Comment by SoManyHs** [comment]
Just noting that ECR will actually error out on you if you have capital letters in a registry name:

```

2019-11-05 16:05:51 UTC-0800 | ECRRepository | CREATE_FAILED | Invalid parameter at 'repositoryName' failed to satisfy constraint: 'must satisfy regular expression '(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*'' (Service: AmazonECR; Status Code: 400; Error Code: InvalidParameterException; Request ID: 8054f715-1408-4246-bb69-7221f159db84)
-- | -- | -- | --



```

**Comment by SoManyHs** [comment]
(For the record, the stack name was "PORJECT-will-totes-deploy")
