### ISSUE TITLE
State of Project

### ISSUE THREAD

**Issue by zbintliff** [aws/amazon-ecs-cli-v2#188]
Hey folks! I'm very excited about this project and have been waiting for it for a bit now. The documentation is a bit sparse now (understandably so), is it in a state where I can pull it down and play with it to understand the UX. Or was the "release" release only intended for the [project roadmap](https://github.com/aws/amazon-ecs-cli-v2/projects/10)?

**Comment by kohidave** [comment]
Hey Zach! 

Feel free to pull it down but It's pretty rough right now so it might not be too fun. We'll have more details coming soon, with some sample docs and workflows. But be ware! It will create resources in your account and we haven't implemented the `destroy` commands yet haha.

**Comment by efekarakus** [comment]
Hi Zach,

The CLI is now in developer preview! https://github.com/aws/amazon-ecs-cli-v2/issues/557 we'd love it if you give it a try :)

**Comment by zbintliff** [comment]
Thanks and congrats! Look forward to testing it out
