### ISSUE TITLE
Pipeline application command

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#214]
Create `ecs pipeline` command to enable CI/CD using Archer.

Subcommands include:
- [x] `pipeline init`: creates a CodePipeline that links project environments (https://github.com/aws/amazon-ecs-cli-v2/issues/249)
- [x] `pipeline update`: updates pipeline for a given project (https://github.com/aws/amazon-ecs-cli-v2/issues/329)
- [ ] `pipeline show`: displays pipeline information
- [ ] `pipeline ls`: shows all pipelines for all (?) projects

Dependent on deploy command? (See #13 )

Related: #210

**Comment by kohidave** [comment]
I think `pipeline init` should create the pipeline.yml and then ask if we want to deploy it. What do you think?

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/amazon-ecs-cli-v2/issues/249

**Comment by efekarakus** [comment]
Resolving this higher level `pipeline` issue as we're creating separate issues per command
