### ISSUE TITLE
Add manual approval to the generated pipeline

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#220]
- [ ] If a stage is a prod stage (i.e. deploying to a prod environment), add a manual approval action in the same CodePipeline stage that will be executed before all the other deployment actions.
- [ ] Also need to surface this as a configurable field in the pipeline manifest

**Comment by SoManyHs** [comment]
Note: `pipeline init` has an `enable-cd` flag that can be passed through for this
