### ISSUE TITLE
Push image to ECR while deploying an application

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#228]
## User story

As a user that has a manifest file for an application and is running `archer app deploy --env name`,  
I want the image to be built and and uploaded to ECR in the appropriate environment,  
So that the image can be pulled after deployment.

**Comment by SoManyHs** [comment]
Noting that the Build stage of the `pipeline` action will also push built images to ECR.

**Comment by sonofachamp** [comment]
This should be resolved by #292 once we're pushing images to the "Project Resources" ECR repository. `app deploy` is currently already pushing images to an ECR repository, but it's a repository created by the `app deploy` workflow itself.
