### ISSUE TITLE
"archer app package" experience

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#229]
### The help menu
```
$ archer app package -h
Prints the CloudFormation template used to deploy an application to an environment.
This command is also run as part of "archer deploy".

Usage
  archer app package [flags]

Flags
  -n, --name string     Name of the application.
  -e --env string       Name of the environment.
  --tag  string         Optional. The application's image tag. Defaults to your latest git commit's hash prefixed with "manual".
  --output-dir string   Optional. Writes the stack template and template configuration to a directory.
  -h, --help            help for package

Examples
  Print the CloudFormation template for the "frontend" application parametrized for the "test" environment.
  $ archer app package -n frontend -e test

  Write the CloudFormation stack and configuration to a "frontend-infra" sub-directory instead of printing.
  $ archer app package -n frontend -e test --output-dir ./frontend-infra
  $ ls ./frontend-infra
  frontend.stack.yml      frontend-test.config.yml
```

### The interactive experience
```
$ archer app package
? Which application's CloudFormation template would you like to generate?
> frontend
> backend
? Which environment's configuration would you like to use for your stack's parameters?
> test
> prod
# Prints the template
```

If the user specified a directory:
```
$ archer app package --output-dir .
? Which application's CloudFormation template would you like to generate?
> frontend
> backend
? Which environment's configuration would you like to use for your stack's parameters?
> test
> prod
✔︎ Success! Wrote the stack template to 'frontend.stack.yml' and template configuration to 'frontend-test.config.yml'
```

## Stories
This command supports two different use-cases:

1. As a user that wants to override a hidden field generated from the manifest,   
I want a command that generates the CFN template and configuration file,   
To find out how the resource names are generated.  
2. Archer's pipeline needs a way of generating the CFN templates and its config files to do deployments.

**Comment by efekarakus** [comment]
@aws/aws-ecs-devx Does this experience makes sense to y'all?

**Comment by kohidave** [comment]
Love it! My only question is if we should allow customers to provide a directory, rather than stack/params file. maybe `--output-dir`

Is your intention to also support "packaging" to cdk through this command at some point?

**Comment by efekarakus** [comment]
> Love it! My only question is if we should allow customers to provide a directory, rather than stack/params file. maybe --output-dir

Will update! 

> Is your intention to also support "packaging" to cdk through this command at some point?

I had not thought of that but it does fit nicely, nice suggestion :)   
We can add flags such as `--cdk bool` to export to CDK

**Comment by SoManyHs** [comment]
I would also support some kind of default output dir, so that it an be consumed by the build step in the pipelines command.

**Comment by sonofachamp** [comment]
> This command is also run as part of "archer deploy".

Should this be `archer app deploy` or is `deploy` a sub-command of root?

What's the plan for when users only have a single application? Should we still prompt, or should we assume the app name? Same question for environments.

Is it possible to combine the template and configuration into a single file that would be pipe friendly?

**Comment by SoManyHs** [comment]
Related: #13

**Comment by efekarakus** [comment]
> I would also support some kind of default output dir, so that it an be consumed by the build step in the pipelines command.

If we support a default for this option, then the command's default behavior becomes to write a directory. I think we want to keep the default to be printing to the screen. The pipeline's build step can do:
`archer app package -n app1 -e env1 --output-dir templates/`

> Should this be `archer app deploy` or is `deploy` a sub-command of root?

I'd go with `archer app deploy`

> What's the plan for when users only have a single application? Should we still prompt, or should we assume the app name? Same question for environments.

We talked about it offline w/ Nick, we won't prompt them if they have a single app and environment but will prompt otherwise.

> Is it possible to combine the template and configuration into a single file that would be pipe friendly?

Talked offline, but yes that's the default behavior! If they provide a directory then we split them into two files :)

**Comment by efekarakus** [comment]
@kohidave What do you think about the proposal below for generating the image tag?

**Assumption**  
We can't get the git commit id in the build stage of the pipeline.

**Proposal**
Our recommendation is to add an optional `--tag` flag to both `archer app package` and `archer app deploy`. By default the tag will be `"manual-{shortHash}"` (e.g. `"manual-13084c0"`)

In the case of the pipeline's build stage, the image tag will be `"pipeline-{buildId}"`. 

**Why?**  
We want `app package` to preview the CFN stack that will be used by `app deploy`. By providing a `--tag` option with a default to both of these commands, we can achieve that.

The flag can then be used by the pipeline, by overriding the default, to generate the template configuration for the stack.

By prefixing the tags with "manual" and "pipeline" users can also distinguishing between an image that was manually pushed or part of pipeline.

**Comment by hencrice** [comment]
Just to document something we discussed offline. Since `app deploy` performs build container images, push container images and deploy in one shot, it's possible that when you run `app deploy` multiple times to deploy to multiple environments, the docker image built&pushed is slightly different per environment even tough they all are all tagged with the same SHA.

One possibility that may result in slightly different container images per build is if you have a non-deterministic command in your Dockerfile, such as `RUN apt-get update`. Although the non-deterministic behavior can be attribute to customers having non-deterministic command in Dockerfile, we can still do better if we can somehow do "build once, deploy everywhere" instead of "build once and deploy once per environment(s)".

**Comment by sonofachamp** [comment]
> **Proposal**
> Our recommendation is to add an optional `--tag` flag to both `archer app package` and `archer app deploy`. By default the tag will be `"manual-{shortHash}"` (e.g. `"manual-13084c0"`)

For the `app deploy` default value is that an `os/exec` call to `git` for this information?

**Comment by efekarakus** [comment]
@sonofachamp 
> For the app deploy default value is that an os/exec call to git for this information?

Yeah, we'll start with that.
