### ISSUE TITLE
`archer app deploy` experience

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#230]
# app deploy experience

## Overview

The goal is to outline what the user experience should be when deploying applications through ecs-cli-v2.

The end state from running the proposed command should be the specified application is deployed and running in the specified environment.

## General flow

* source inputs from user
  * application name to deploy
  * environment name to deploy the application to
* build the input application name image locally via the docker API
* push the image to input environment ECR
* invoke the `archer app package` workflow with the application name, environment name, and image inputs
  * result of package workflow will be a fully formed CloudFormation template
* apply the CloudFormation template to the given environment via CloudFormation API

## Proposed command

`archer app deploy --name <application-name> --env <environment-name>`

#### `--name`

The application name that was previously generated via `archer app init` workflow. If the `--name` flag was not provided on invocation we will prompt the user with a list of application name options pulled from SSM.

If there are no applications associated with the project return an error.

If there is a single application associated with the project we will default to that application's name and log this assumption to the user.

If the flag input application name isn’t found to be associated with the project return an error.

##### Application name prompt

```sh
Which application would you like to deploy?
> FirstApp
> SecondApp
```

#### `--env`

The environment name that was previously generated via the `archer env init` workflow. If the `--env` flag was not provided on invocation we will prompt the user with a list of environment options pulled from SSM.

If there are no environments associated with the project return an error.

If there is only one environment we will default to that environment's name and log the assumption to the user.

If the flag input environment name isn’t found to be associated with the project return an error.

##### Environment name prompt

```sh
Which environment would you like to deploy <application> to?
> dev
> prod
```

#### `--tag`

The tag to apply when building the Docker image.

If not provided we will make an `os/exec` call to get the short hash of the repository and append it to `manual-<short-hash>` as the default value.

## Workflow dependencies

* The user must have already initialized an environment
* The user must have already initialized an application
* The `archer app package` workflow that will generate a CloudFormation template which represents an application deployment to an environment
* `git` must be on the users path for defaulting the `--tag` flag value when not provided

**Comment by efekarakus** [comment]
Looks great :shipit: ! Should we include a `--tag` option like https://github.com/aws/amazon-ecs-cli-v2/issues/229#issuecomment-545642212 ?

**Comment by kohidave** [comment]
Awesome. One question - what do you think about (eventually) taking an image in so that we can skip builds all together.

`archer app deploy --image myprebuiltimage/12345`

**Comment by sonofachamp** [comment]
@kohidave I don't see why not. Would that include external private repository support? That could also impact the `app package` workflow?

**Comment by sonofachamp** [comment]
Created #291 to limit application options by local workspace instead of all applications in SSM.

**Comment by sonofachamp** [comment]
Created #292 to update the ECR logic once #290 is creating the ECR repositories.
