### ISSUE TITLE
Consolidate the `archer.pipeline` interface and the `archer.manifest` interface

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#244]
Ideally, there should be only 1 interface that represents the various types of manifests: pipeline and application. Both can be marshaled to the manifest file format, CFN template (and maybe more in the future).

For now `manifest.pipeline` is the only entity that behaves that way so we created a new `archer.pipeline` interface to limit the amount of changes such that the implementation of application manifest does not need to change right now.

We can refactor them once we have time.

**Comment by efekarakus** [comment]
I think right now we probably shouldn't even return interfaces for manifests, it was probably a code smell to return one.

I'll resolve this as we can do these refactors whenever we need to add a new application pattern.
