### ISSUE TITLE
Add User-Agent to SDK calls

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#255]
In order for us to track cliv2 usage, we should include a unique user agent in our AWS SDK calls. One example of how to do that is [here](https://docs.aws.amazon.com/sdk-for-go/api/aws/corehandlers/)

**Comment by efekarakus** [comment]
copy/paste https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/clients/user_agent.go
