### ISSUE TITLE
Update `app init` workflow when asking user to select a Dockerfile

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#275]
Update `AppInit` to add the "/Dockerfile" at the end of the options to keep the current UX.

The paths have been modified from the original implementation to output the directories containing the `Dockerfile`s.

For example a user might now be prompted to select which Dockerfile to associate with an app like this:
```
Which Dockerfile would you like to use for <app-name> app?
> .
> frontend
> backend
```

but we'd like it to be:
```
Which Dockerfile would you like to use for <app-name> app?
> ./Dockerfile
> frontend/Dockerfile
> backend/Dockerfile
```

Another option could be to simply update the question to say something like:
```
Which directory is the Dockerfile in that you want to associate with this application?
> .
> fontend
> backend
```
and leave the new paths unchanged.

_Originally posted by @efekarakus in https://github.com/aws/amazon-ecs-cli-v2/pull/272_

**Comment by kohidave** [comment]
Additionally, we can probably skip asking if there's another location they'd like to manually enter. I understand it's to help us if the Dockerfile is nested deeper than 1 dir, but I think that'll be uncommon, and asking for the path can lead to confusing experiences (if they point to a dockerfile outside of their workspace).

**Comment by sonofachamp** [comment]
@kohidave yeah for sure, I think we should create a separate issue for that to remove the "Enter a customer" path option if I'm understanding your suggestion correctly?

**Comment by sonofachamp** [comment]
The changes made are including the `/Dockerfile` value as part of the path written to the application manifest file. The selections shown to the user can include `/Dockerfile`, but the actual value written to the manifest should be only the folder containing the `Dockerfile` to be friendly to `app deploy`.
