### ISSUE TITLE
`env init` workflow can't write env SSM entry if user cancels during active deployment

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#301]
If a user runs `env init` to kick off an active deployment then subsequent `env init` invocations return `✔ Success! Environment test already exists under project myproj! Do nothing.` even if the CloudFormation Stack Status is `CREATE_IN_PROGRESS`.

It might be more clear to the user if we can return a message that informs them when a deployment is already underway for the given inputs, or potentially resumes the progress outputs.

**Comment by sonofachamp** [comment]
There also appears to be an unintended side affect of not being able to store an environment into SSM if an environment CloudFormation stack was created, but the user cancelled (`Ctrl-c`ed) out before a deployment fully completes and a `CreateEnvironment` call happens.

Example workflow to reproduce:
```
$ ./bin/local/archer env init test
...progress of environment being created...
$ ^C
$ ./bin/local/archer env init test
$ ✔ Success! Environment test already exists under project myproj! Do nothing.
```
Meanwhile in SSM there is no `test` environment entry.

We may need to make the `CreateEnvironment` call in the case where we handle `cloudformation.ErrStackAlreadyExists` error or do an existence check in SSM before making the `CreateEnvironment` call.

**Comment by kohidave** [comment]
Yea essentially right now we're only checking to see if a stack exists, regardless of its status. We only want to skip creating it if its in some successful state.

**Comment by sonofachamp** [comment]
So maybe we need to add in a `DescribeStack` call if the stack does already exist and write the environment to SSM if the status is "success" and that environment doesn't already exist in SSM?

Or switch that order of operations:
* `DescribeStack` to see if the stack exists
  * If it doesn't exist then `CreateStack` and write to SSM
  * If it does exist ensure it succeeded and validate/write to SSM
