### ISSUE TITLE
Init workflow missing profile flag

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#317]
### Description

The `--profile` flag that's available in `"env init"` is missing in the `"init"` command.
This means that we deploy the "test" environment in the user's default profile (where the project infrastructure is created) instead of possibly a different profile.

### Expected Behavior
If the user decides to deploy their application to a staging environment, we should consider prompting them for which profile they'd like to use for their "test" environment.

**Comment by SoManyHs** [comment]
Note: Should `--profile` be a global flag (or have a larger scope than for `init`?

**Comment by efekarakus** [comment]
Related https://github.com/aws/amazon-ecs-cli-v2/issues/618
