### ISSUE TITLE
`app delete` spec

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#322]
# app delete

## Overview

The goal is to outline what the `app delete` command should do and how it will accomplish application deletion.

The end state from running the proposed command should be the specified application is deleted from the specified environment(s?) and all resources related to the specific input application deployment are cleaned up.

## General flow

* source inputs from user
  * application name to delete
* verify the application and environment both exist
* Delete all app deployment stacks across associated environments
* Empty ECR repositories in all associated environment regions
* Update project resources to remove app ECR repositories
* Delete the app SSM parameter
* Delete the local workspace app manifest file

## Proposed command

`archer app delete <app-name>`

#### `--yes`

Skips confirmation question before deleting the application from the project.

## Workflow dependencies

* The user must have already initialized an environment
* The user must have already initialized an application
* The input application must be deployed somewhere

## Outstanding Questions

* How do we want to distinguish `delete` from `undeploy`
* Does `delete` imply application re-initialization would be required (`app init`)?

**Comment by SoManyHs** [comment]
Related to https://github.com/aws/amazon-ecs-cli-v2/issues/98 -- should we close the older issue?

**Comment by sonofachamp** [comment]
> Related to #98 -- should we close the older issue?

Maybe. I think there might need to be a distinction between `delete`/`undeploy` vs. `destroy` or whatever equivalent names we come up with.
