### ISSUE TITLE
"archer env delete" experience

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#352]
### Help menu
```bash
$ archer env delete -h
Deletes one or more environments from your project.

Usage
   archer env delete [name]... [flags] 

Flags
  -h, --help               help for init
      --yes                Skips confirmation prompt. (default false)

Global Flags
  -p, --project string   Name of the project.

Examples
  Delete the "test" and "prod" environments.
  `$ archer env delete test prod`

  Delete the "test" and "prod" environments without prompting.
  `$ archer env delete test prod --yes`
```

### The interactive experience
```bash
$ archer env delete test prod
? Would you like to delete environment test in project phonetool? [y/N] y
⠼ Deleting environment test.
? Would you like to delete environment prod in project phonetool? [y/N] N
Skipped deleting test.
```

### Errors
If the environment has already existing applications.
```bash
$ archer env delete test --yes
Error: environment test has the following applications still running: app1, app2.
Please run `archer app delete app1 app2 --yes` first.
```

If the environments do not exist in the project.
```bash
$ archer env delete test prod --yes
Error: environment prod does not exist in project phonetool.
```

If the environment stacks are not available in the environment's region and assumed role.
```bash
$ archer env delete test prod --yes
Error: environment prod does not exist in account 12345 and region us-west-2. 
```

### Follow-up steps
Display progress of deletions just like in `env init`.

**Comment by sonofachamp** [comment]
Should we consider not supporting multiple input resources for deletion? I'm weary of it because it makes mass destruction much easier. If we do support it we should outline how we want to handle communication of combination failure/success. For example, if test and prod do exist and we are able to delete test, but not prod, that's a partial completion scenario.

**Comment by efekarakus** [comment]
> Should we consider not supporting multiple input resources for deletion? I'm weary of it because it makes mass destruction much easier, especially with a "global" confirm flag.

Mm yeah I agree that it makes mass destruction easier but that was the intention. The idea was taken from the CLI talk:
![Screen Shot 2019-11-15 at 10 59 14 AM](https://user-images.githubusercontent.com/879348/68968278-04c99f80-0797-11ea-8386-bc035cfae59c.png)


> For example, if test and prod do exist and we are able to delete test, but not prod, that's a partial completion scenario.

I was thinking that this operation would be idempotent (if the env does not exist skip it), so even if one environment fails to be deleted they can re-run the command later with the same args to get the desired effect.

But overall I agree with you, we can start off smaller :) I'll first put up a PR without multiple args and see what we think afterwards from there.
