### ISSUE TITLE
Store EnvironmentManagerRole in SSM

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#361]
The `environment/cf.yml` template includes creation of the `EnvironmentManagerRole` resource. We need to capture that output on environment creation and store it in SSM.

The `app deploy` flow should be updated to utilize this EnvironmentManagerRole to support multi-account use-cases.

**Comment by efekarakus** [comment]
We need it for `app delete` and `env delete` as well I believe

**Comment by efekarakus** [comment]
I'll pick this up! thanks Nick
