### ISSUE TITLE
Bug Bash Feedback: spinner sometimes works on Windows PowerShell

### ISSUE THREAD

**Issue by srrengar** [aws/amazon-ecs-cli-v2#368]
Printed a lot of new lines each time the spinner moved on project creation, but it worked when deploying an environment

![image](https://user-images.githubusercontent.com/30325699/68974345-5f69f800-07a5-11ea-95dd-7c924e2b548e.png)

**Comment by efekarakus** [comment]
We fixed this in the spinner library!
