### ISSUE TITLE
Bug Bash Feedback: tag name has to be given when running `archer app deploy`

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#370]
After I created my cool project, I want to deploy my project so I run `archer app deploy` then it gives error as follow:

```
Only found one app, defaulting to: my-app
Only found one environment, defaulting to: test
Error: defaulting tag: exit status 128
```

Then, I ran `archer app deploy --tag latest`, it started deploying my application. I expect by default archer will give a default tag for my application if I do not specify one.

**Comment by sonofachamp** [comment]
We try to run `git describe --always` to get a tag if you don't provide one. Are you inside a git repository when you ran the command?

**Comment by iamhopaul123** [comment]
Nope. I am not in a git repo.

**Comment by sonofachamp** [comment]
We can probably bake something in to check if you're inside of a git repo or not to more gracefully handle this scenario.

Potentially `git rev-parse --is-inside-work-tree`

**Comment by efekarakus** [comment]
I believe this is resolved now:
https://github.com/aws/amazon-ecs-cli-v2/blob/84f02ce9cda4c80b57bdca2cbd4e724969332f54/internal/pkg/cli/app_deploy.go#L304-L315

If there is an error while retrieving a tag value from git, we prompt the user for a value
