### ISSUE TITLE
Bug Bash Feedback: env init breaks on mac os when adding another environment after initial deployment

### ISSUE THREAD

**Issue by bvtujo** [aws/amazon-ecs-cli-v2#371]
Mac Os

When I deploy the test app for this bugbash, then run `./archer env init` again, I see the following output. I tried this again after refreshing my temp credentials from isengard but saw the same error. 
```bash
./archer env init
? What is your environment's name? prod
✘ Error! Failed to accept changes for the prod environment.
Error: failed to create changeSet for stack myCoolApp-prod: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, default.
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials/: dial tcp 169.254.169.254:80: connect: host is down
```

**Comment by sonofachamp** [comment]
So the `env init` flow `--profile` flag defaults to `default`, so this was failing to find valid credentials as part of your default profile. I think having a valid access key and secret in your default profile under `/.aws/config` would fix this issue, but we definitely need to consider user workflows that are using environment variables.

**Comment by bvtujo** [comment]
Yeah, this is closable--I was not taking into account that the tool was looking in my default aws profile. I think perhaps this could be resolved by logging a debug or info statement for verbose purposes that indicates where archer looks for credentials, and what set of credentials it chooses.

**Comment by efekarakus** [comment]
Closing this as this is expected!
