### ISSUE TITLE
CodeBuild role policy needs SSM and CFN permissions

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#377]
CodeBuild role policy used in the pipeline needs arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess and arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess bc archer CLI needs access to these services while it runs in the Build stage.

**Comment by kohidave** [comment]
I added:

`AmazonSSMReadOnlyAccess`, `AWSCloudFormationReadOnlyAccess` and ECR push permissions.
