### ISSUE TITLE
Rename binary and update UX messages which reference commands

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#400]
Right now the binary is `archer` - we'd like to change it to `ecs-preview`.

We'd also like to update the help text to include this new name.

**Comment by sonofachamp** [comment]
Do we want to rename go packages as well?

**Comment by sonofachamp** [comment]
Also what about the SSM path values? Should we change those as well or maybe rename them to be binary-name agnostic so that we don't have to change them again in the future?
