### ISSUE TITLE
Update buildspec to produce "latest" flag

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#402]
We want to produce -latest binaries in our pipeline .

**Comment by sonofachamp** [comment]
I thought we didn't like supporting a `latest` tag? Can we tag it something like `0.0.0-alpha1` or something along those lines instead?

**Comment by kohidave** [comment]
I was thinking it'd make the blog post easier to link to the "latest" binary - but I think we can just link to the getting started page on our GH. So we'll just not do the latest thing, because yea, it's confusing.
