### ISSUE TITLE
Make environment creation in `init` workflow profile aware

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#409]
When a user opts to create an environment during the `init` workflow that environment will always be created using the `"default"` profile. We should enable users to specify a profile name and/or region or prompt them with a list of profile options with which to create the environment against.

**Comment by sonofachamp** [comment]
I believe #608 resolves this specific case, correct me if that's wrong @efekarakus

**Comment by efekarakus** [comment]
Correct!
