### ISSUE TITLE
Don't continue asking for more env to add to the pipeline if there's no more

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#410]
During Nathan's testing, he ran into this case where archer keeps prompting for more environments to add to the pipeline even when there's no more to add:

![Screen Shot 2019-11-19 at 3 56 33 PM](https://user-images.githubusercontent.com/3822365/69187109-c9004400-0ace-11ea-974d-5a5a68e22a20.png)

**Comment by kohidave** [comment]
Assigning this to our newest and greatest member!
