### ISSUE TITLE
Include info regard the scopes needed for the GitHub personal access token

### ISSUE THREAD

**Issue by hencrice** [aws/amazon-ecs-cli-v2#411]
Suggested by Nathan:

> The personal access token for the GitHub repository linked to your workspace. For more information on how to create a personal access token, please refer to: https://help.github.com/en/enterprise/2.17/user/authenticating-to-github/creating-a-personal-access-token-for-the-command-line.
> 
> We should include info about what scopes are required.

**Comment by efekarakus** [comment]
Looks like we added this!
https://github.com/aws/amazon-ecs-cli-v2/blob/84f02ce9cda4c80b57bdca2cbd4e724969332f54/internal/pkg/cli/pipeline_init.go#L393
