### ISSUE TITLE
Bug Bash Feedback: need to select which application after declining to create a staging environment

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#428]
I have one project and under the project I have two application called 'lb-app' and 'my-app'. The error can be reproduced as follow:

<img width="547" alt="Screen Shot 2019-11-20 at 9 26 00 AM" src="https://user-images.githubusercontent.com/51377557/69263080-762f9680-0b79-11ea-84bb-b55b9ac077b7.png">

**Comment by efekarakus** [comment]
#440 doesn't fix this issue, https://github.com/aws/amazon-ecs-cli-v2/issues/436 is the same issue tracking the progress there.

**Comment by sonofachamp** [comment]
It fixes the issue of being prompted at all when you say `N` to deploying a staging environment.

**Comment by efekarakus** [comment]
Yeah I think this issue had two problems :P I should have said doesn't completely fix the issue.
