### ISSUE TITLE
Bug Bash Feedback: archer init

### ISSUE THREAD

**Issue by pkandasamy91** [aws/amazon-ecs-cli-v2#432]
Running archer init gives me the prompt twice once for the instructions and once I select a value.

<img width="568" alt="Screen Shot" src="https://user-images.githubusercontent.com/44981951/69266365-e3462a80-0b7f-11ea-8c32-b9bdddcfaf7e.png">

**Comment by efekarakus** [comment]
I believe this is the same bug as: https://github.com/aws/amazon-ecs-cli-v2/issues/125

Closing this one to track it there!
