### ISSUE TITLE
Would be better to have "app ls"

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#439]
Currently archer does not have "app ls". As a user I have a project called "my-project". 

However, I forget what applications I have under that project and I find there's no easy way to show my applications.

**Comment by iamhopaul123** [comment]
Just found #322, which is the same as the second use case.

**Comment by kohidave** [comment]
`archer app ls` would be awesome. It can behave just like `env ls`. One nice addition is if we included an `--local` flag, which showed only the apps checked out in this workspace.

**Comment by iamhopaul123** [comment]
> `archer app ls` would be awesome. It can behave just like `env ls`. One nice addition is if we included an `--local` flag, which showed only the apps checked out in this workspace.

I'll open another issue for --local flag for both `app ls` and `env ls`.
