### ISSUE TITLE
`env delete` AccessDeniedException - tag:GetResources

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#444]
After running the `init` workflow, running `env delete test` returns an error:
```
→ ./bin/local/archer env delete test
Error: find application cloudformation stacks: AccessDeniedException: User: arn:aws:sts::<accoun-number>:assumed-role/myproj-test-EnvManagerRole/1574290136154061274 is not authorized to perform: tag:GetResources
        status code: 400, request id: 8daa4dfd-193c-4701-8292-daac10dbcf52
```

**Comment by efekarakus** [comment]
mmm odd, can you check the role itself in the console to make sure that the permissions are not there?

**Comment by efekarakus** [comment]
I wonder if that's some legacy role that was created before the latest changes

**Comment by sonofachamp** [comment]
Yeah the permissions are not on the role, but it is in the `cf.yml` template. Not sure how I managed it, probably just user error, will retry fresh and reopen if issue persists.

**Comment by efekarakus** [comment]
Yeah my guess is that the "test" environment was created with an older version of the CLI before the "env delete" changes :)
