### ISSUE TITLE
App Deploy doesn't work when changing manifest files

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#460]
When you run app deploy, it doesn't update the changes the template with the manifest file values. The deployment fails because there are no changes.

I believe this is because we pass in the manifest values as parameters, and we're not passing parameters in when we run app deploy.

**Comment by sonofachamp** [comment]
Is there a specific value change in the app manifest file you're not seeing picked up?

I can increase task counts and redeploy and everything works fine. The `app package` workflow spits out a single CloudFormation template that should contain the latest app manifest parameters, so I don't think we need to specify any parameters when deploying the template.

**Comment by kohidave** [comment]
I think when I did it, I only changed the rule path - no other changes.

**Comment by kohidave** [comment]
Ah - I think i've figured it out. We don't clean up failed changesets in app deploy, so if an empty changeset exists and we try to redeploy, it will fail because the empty changeset with the same name exists.

I'll update it to have a random bit in the name for now.
