### ISSUE TITLE
Check no changes err in DelegateDNS in cf/project.go

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#467]
Right now, in the `DelegateDNS` function in `project.go`, we call update [here](https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/deploy/cloudformation/project.go#L93). If there's an error, we bubble it up and it eventually stops environment creation, this is fine.

We should, however, swallow the `errChangeSetEmpty` error - since it just means there were no updates needed. 

Right now, if you run env init twice, and this delegation was successful the first time, it will cause the the update to fail.

**Comment by efekarakus** [comment]
?????????????????

**Comment by efekarakus** [comment]
????????????????????????????????????????????????????????????????????????????????

**Comment by sandyleo26** [comment]
happy to take on this. is it ok for non-first time contributor to tackle another "good first issue"?

**Comment by efekarakus** [comment]
Hi @sandyleo26! 

It's totally okay for a non-first time contributor to tackle another "good first issue"! They're used more as an indicator on how much prior knowledge you might need about the codebase.
