### ISSUE TITLE
Allow subdomain in 'project init --domain'

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli-v2#473]
I want to set up a project using subdomain 'archer.reinvent-trivia.com', to reduce blast radius from the root domain reinvent-trivia.com.

I get:
```
$ archer project init --domain archer-test.reinvent-trivia.com
Looks like you are using a workspace that's registered to project clares-demos. We'll use that as your project.
Error: get domain details for archer-test.reinvent-trivia.com: UnsupportedTLD: reinvent-trivia.com tld is not supported
	status code: 400, request id: 5d2bd74a-f6df-463a-86e2-245c824876ab
```

I'm guessing this is splitting on the first period it finds, and assuming the format is 'domain.tld' vs 'subdomain.domain.tld'?

**Comment by kohidave** [comment]
Oh that’s a good point. Perhaps we can loosen up to check to make sure you have a hosted zone with the right name.
