### ISSUE TITLE
Improve app delete and env delete experience

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#523]
Currently when outside of the project repo, it fails to get the project when trying to delete an environment or application. If in the project repo, `app delete` requires a flag specifying the application name before deleting. And `env delete` prompts user to input the env name. Would be better to select env name from a list when `env delete` and `app delete`.

1.  If outside of a project repo, it prompts user to select a project, then prompts to select an application/env to delete.

2.  If in a project repo, shows an application/env list to select to delete.

**Comment by sonofachamp** [comment]
`app delete` must happen inside of a workspace to ensure we can delete the application manifest file.

**Comment by efekarakus** [comment]
We've been creating a smaller issues to tackle these usability bugs, resolving this one.

I believe we also added listing the environments in env delete
