### ISSUE TITLE
Vague purpose for Validate() func

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#524]
`Validate()` should only be responsible for checking the validation for the flag input. However, now in some modules (e.g., env, pipeline) Validate function also validate user input in `Ask()`. As a result, `Validate` is called in both "preRun" section (which is correct) and "Run" section after `Ask()` (which should not happen). Ideally I think it would make more sense to validate user input right after they input, instead of throwing an error after the whole `Ask()` finishes.

**Comment by iamhopaul123** [comment]
related to #522, #515

**Comment by efekarakus** [comment]
This is done! We refactored the code base for all commands to follow the pattern `Validate`, `Ask` and `Execute`, explanation:
https://github.com/aws/amazon-ecs-cli-v2/blob/84f02ce9cda4c80b57bdca2cbd4e724969332f54/internal/pkg/cli/cli.go#L50-L63
