### ISSUE TITLE
Add resource tags to Cloudformation templates

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#54]
Add [Resource tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) to applicable resources in our `environment.yml` and `loadbalanced-fargate-service.yml` CloudFormation templates.

### Related
#9

**Comment by efekarakus** [comment]
Tags are applied on the CFN tag and propagated down
