### ISSUE TITLE
Should remove mocks for iface interface in client package

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#541]
Currently part of our mocking strategy depends on the AWS SDK's `iface` package. If they add a new method our mock will easily fail when bumping to a new SDK version. Ideally we should create wrapper interfaces and mock them. Here's a list of `iface` that we mock directly:

- ecriface

- stsiface

- cloudformationiface

- secretsmanageriface

- ssmiface

- resourcegroupstaggingapiiface

Also, it will be great if we can move wrapper interfaces into one file so that we can easily locate them.

**Comment by efekarakus** [comment]
We're doing this as a new SDK go change breaks the build, past commit for reference on how to do this:
https://github.com/aws/amazon-ecs-cli-v2/commit/b9ffbdfa3f1aae1e30297dcdfb62e243bb807d86
