### ISSUE TITLE
disable pagination

### ISSUE THREAD

**Issue by mzemanek1** [aws/amazon-ecs-cli-v2#544]
Is there is way to disable pagination ?   I will never want it and don't want it to break my scripts?  

Thanks

**Comment by iamhopaul123** [comment]
Hi @mzemanek1, can you describe the issue more specifically? Like pagination for which part and could you also provide the command and the corresponding error log?

**Comment by kohidave** [comment]
Hi friend - I'm going to close this issue. I think you probably meant the AWS CLI :)
