### ISSUE TITLE
History / changelog?

### ISSUE THREAD

**Issue by mwarkentin** [aws/amazon-ecs-cli-v2#560]
Now that it looks like ecs-cli-v2 has made it into preview - are you maintaining a history / changelog file anywhere? Or noting release notes in the github releases?

Thanks!

**Comment by efekarakus** [comment]
Hi @mwarkentin !

We don't have a CHANGELOG yet, but we're planning to add release notes to future GitHub releases so you can see what changed :)

**Comment by mwarkentin** [comment]
Sounds good!
