### ISSUE TITLE
Implement `ecs project delete` subcommand

### ISSUE THREAD

**Issue by santosh07bec** [aws/amazon-ecs-cli-v2#580]
I see there is no command exists to delete a project. Is there any plan to implement the same?

$ ecs -h
Launch and manage applications on Amazon ECS and AWS Fargate.

Commands 
  Getting Started ✨
    init        Create a new ECS application.
 
  Develop 🔧
    project     Project commands.
    env         Environment commands.
    app         Application commands.
 
  Release 🚀
    pipeline    Pipeline commands.
 
  Settings ⚙️
    version     Print the version number.
    completion  Output shell completion code.

Flags
  -h, --help      help for ecs-preview
      --version   version for ecs-preview

Examples
  Display the help menu for the init command
  `$ ecs-preview init --help`

**Comment by efekarakus** [comment]
Yup! It's being worked on right now :) you can track it here: https://github.com/aws/amazon-ecs-cli-v2/issues/573

**Comment by efekarakus** [comment]
Resolving this issue for tracking it at https://github.com/aws/amazon-ecs-cli-v2/issues/573  instead.
