### ISSUE TITLE
`ecs-preview init` needs to be able to set port number correctly

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#595]
Ideally users should be able to run `ecs-preview init` to create a deployed application that can work well. However, currently if you have an application that does not use port `8080`, then you need to do `app deploy` after making changes to the generated manifest file.

It would be better to add another prompt to get the port number the user would like to use before prompting if they'd like to deploy the app. This prompt only appears if they are creating a load balanced web app.

```
? Which port would you like to use to deploy "my-app"? [? for help] (8080)
5000

? Would you like to deploy a test environment?
```

We can also get the default value for them by parsing their `dockerfile` (set it to `8080` by default if their `dockerfile` does not specify any port).

**Comment by iamhopaul123** [comment]
related to #469

**Comment by efekarakus** [comment]
resolving in favor of https://github.com/aws/amazon-ecs-cli-v2/issues/703
