### ISSUE TITLE
Expose health check path in manifest

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#597]
Right now, the health check is hardcoded to `/` - we should let folks specify that from the manifest.

**Comment by SoManyHs** [comment]
Do we want customers to be able to pass this in through a flag on the app init command, or simply expose the field in the manifest itself?

**Comment by SoManyHs** [comment]
Note: this will just be a top-level field in the app manifest

**Comment by SoManyHs** [comment]
Will probably keep default to just be `/`
