### ISSUE TITLE
Add error handling on return value from newInitOpts() func in cli/init.go

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#615]
This occurs due to missing error handling on the return value from `newInitOpts()` function in `internal/pkg/cli/init.go`:
https://github.com/aws/amazon-ecs-cli-v2/blob/7683a47d6d23daa3bbc2314f89d8084396150dcd/internal/pkg/cli/init.go#L232

I was getting this output due to not having a `~/.aws/config` file, the `ini` package was returning an error that went unhandled:
```
./bin/local/ecs-preview --version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xd6c3f8]

goroutine 1 [running]:
github.com/aws/amazon-ecs-cli-v2/internal/pkg/cli.BuildInitCmd(0x10102e0)
        <redacted>/amazon-ecs-cli-v2/internal/pkg/cli/init.go:257 +0x1d8
main.buildRootCmd(0x0)
        <redacted>/amazon-ecs-cli-v2/cmd/ecs-preview/main.go:51 +0x104
main.main()
        <redacted>/amazon-ecs-cli-v2/cmd/ecs-preview/main.go:24 +0x22
```

**NOTE:** This affects all subcommands since the error occurs within the scaffolding code `BuildInitCmd()`.

I think the ideal path forward here is to bind flags using viper instead of binding to the opts struct directly. This should enable us to invoke `newInitOpts()` in the `RunE` function where we can properly handle errors.

**Comment by iamhopaul123** [comment]
Can we move `newInitOpts()` to "preRun" section so that the error can be handled properly? Like what we did in other files?

**Comment by sonofachamp** [comment]
Sure, I think any of the functions that enable us to handle the error properly would work fine. The only downside I can see is the variable has to be in the `BuildInitCmd()` function scope since it's referenced in all of the `*Run` functions.

**Comment by iamhopaul123** [comment]
That's a good call out. How about we initiate those variables that don't need error handling first. Then, `newInitOpts()` is responsible for handling the rest of them that need error handling but can be initiated in "preRun" section. And for those variables that can only be initiated in the middle of the run part (depending on the other resources got from users), we create func like `initDescriber` as a variable (for initiating "Describer").
