### ISSUE TITLE
"app delete" unit test not fully covered

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#616]
In "app delete" `Execute()` part, we have:

- sourceProjectEnvironments()

- deleteStacks()

- emptyECRRepos()

- removeAppProjectResources()

- deleteSSMParam()

- deleteWorkspaceFile()

Only `sourceProjectEnvironments()` is covered in the unit test. We need to cover the rest functions as well.

**Comment by SoManyHs** [comment]
Related: https://github.com/aws/amazon-ecs-cli-v2/issues/641
