### ISSUE TITLE
Incorrect app url if multiple apps deployed in the same environment

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#619]
For example, two applications `my-app` and `bad-app` is created with the same Dockerfile and are deployed in environment `test`. When I run `app show`, it gives me the same url for both `my-app` and `bad-app`.

Actually those two apps do not need to be built from the same Dockerfile. The problem is because of the fact that we create one load balancer per environment. And if "path" is not specified, they are both default to "*", which causes the second app to be ignored.

I think this is an edge case. However, we can possibly prevent users from deploying two applications to the same environment using the same path.

**Comment by SoManyHs** [comment]
I run into this problem as well even with two separate dockerfiles. End up having to change some paths manually in one of the app manifests and ensuring my application code knows how to handle those routes.

**Comment by kohidave** [comment]
Related #598

**Comment by SoManyHs** [comment]
I wonder if there is a way to make this more painless by having default path rules somehow set up in the ALB, if we are working under the assumption that having multiple apps behind the same load balancer is the most common infrastructure pattern?

**Comment by iamhopaul123** [comment]
Related #598
