### ISSUE TITLE
Enable interactivity bypass for "project delete" subcommand

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#629]
#609 added the `project delete` subcommand.

One issue encountered when building this out is that `env delete` workflow requires the user to specify a profile to be used when deleting the resources. We enabled the interactivity to prompt the user for a profile when deleting an environment to enable the feature to work for now, but ideally users should be able to bypass the interactivity.

Some challenges:
* if we take in profile names via flags there's no straightforward way to associate a profile with an environment
* storing profile names is not reliable since that profile name is completely arbitrary and could differ from machine to machine

We should discuss different mechanisms we can potentially use to relate profiles to environments to enable cleaner experiences not only in `project delete`, but also other workflows that rely on the "default" profile.

Refer to [this comment](https://github.com/aws/amazon-ecs-cli-v2/pull/609#discussion_r372115684) to understand the existing experience.

**Comment by SoManyHs** [comment]
Fixed in https://github.com/aws/amazon-ecs-cli-v2/pull/658
