### ISSUE TITLE
`pipeline delete` experience

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#630]
### Help menu
```bash
$ ecs-preview pipeline delete -h
Deletes given pipeline from your project

Usage
   ecs-preview pipeline delete ... [flags]

Flags
  -h, --help               help for init
      --yes                Skips deletion confirmation prompt (default false).
     --delete-secret  Deletes SecretsManager secret that stores the auth token associated with the source stage of the pipeline (default false).

Global Flags
  -p, --project string   Name of the project.

Examples
  Delete the pipeline associated with your project.
  `$ archer pipeline delete `

  Delete the pipeline associated with your project without prompting
  `$ archer pipeline delete --yes --delete-secret`
```

### The interactive experience
```bash
$ archer pipeline delete
? Are you sure you want to delete the pipeline associated with this project? [y/N] y
? Would you like to delete the secret <secret_name> associated with this pipeline? [y/N] y
⠼ Deleting stored secret <secret_name>.
```

### Errors
If the pipeline has active builds in progress.
```bash
$ archer env delete test --yes
Error: There is currently an active build for pipeline <name>. Please try again when build is finished.
```

If there is no pipeline.yml in the project.
```bash
$ archer pipeline delete --yes
Error: no pipeline associated in project <project_name>.
```

### Follow-up steps
Display progress of deletions just like in `env delete`.

**Comment by bvtujo** [comment]
Does it make sense to have a separate flag to delete without confirmation but retain the secret? The use cases seem like the following:

1. I naively call `pipeline delete` because I haven't yet had to think about the particulars of how this method workds
2. I call `pipeline delete --yes` because I know I want to delete everything but want to keep the secret
3. I call `pipeline delete --yes` and want to delete everything, I'm done with it. 

In 2. is there a chance that I'll stop myself from being able to deploy pipelines with the same Github token for 7 days until the secret fully goes away? Does the possible user confusion from case 2 warrant complexity of an extra flag?

**Comment by efekarakus** [comment]
:shipit: 

@bvtujo we could bypass the 7 days wait I believe with the `ForceDeleteWithoutRecovery` parameter https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#DeleteSecretInput

**Comment by bvtujo** [comment]
@efekarakus that's good, I think that's my only issue here. As long as we definitely destroy the token when the user specifies `--yes` then :shipit:

**Comment by kohidave** [comment]
Yay! Thanks for this design. Just curious, why stop if there's an active build? Will CF yell at us if we try to delete a CodeBuild project that has an active build?

**Comment by SoManyHs** [comment]
@kohidave not sure. The original thought was that it might leave an environment in a weird state, but I can double check what the CFN behavior is. Do you think it's a better experience to just delete anyway if there's a build going?

**Comment by SoManyHs** [comment]
Addresses https://github.com/aws/amazon-ecs-cli-v2/issues/626

**Comment by SoManyHs** [comment]
Do we want to specify `--app` as a flag, in case a project has multiple pipelines?

**Comment by SoManyHs** [comment]
Just kidding, ideally we expect only one `pipeline.yml` file per workspace.
