### ISSUE TITLE
Expose Log Retention in Manifest and/or update it to not be forever in Environments

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#651]
Right now we set the log retention to be forever. This is not good, and is pretty unreasonable.

I think we can update the log groups to have a default retention and then perhaps let customers override it in their manifests.

Just ball parking, but I'm thinking non-prod environments ~ 1 month, prod environments ~3 months?

**Comment by SoManyHs** [comment]
Default set retention to 1 month. In the future, we'd like to make this configurable.

**Comment by SoManyHs** [comment]
For custom resources, we should set log retention to be much shorter (1 day? 1 week?), since this is only important for deploying said resources.
