### ISSUE TITLE
Make "env" subcommands idempotent

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli-v2#660]
Currently, `env ls` depends on a call to Systems Manager to list the environments. However, if the associated CFN stack for that environment has been deleted, `env ls` will still succeed. 

This may also affect issues with adding environments in a pipeline, e.g.

Related: 
- https://github.com/aws/amazon-ecs-cli-v2/issues/301
- App init idempotency: https://github.com/aws/amazon-ecs-cli-v2/issues/552

**Comment by SoManyHs** [comment]
Similarly, `env delete` will fail if the CFN stack for the environment was deleted outside of this tool:
```
~/aws-reinvent-2019-trivia-backend(master)$ ecs-preview env delete

? Which environment would you like to delete? prod

? Which named profile should we use to delete prod? default

? Are you sure you want to delete environment prod from project backend? Yes
✘ Failed to delete environment prod from project backend: failed to find a stack named backend-prod.

~/aws-reinvent-2019-trivia-backend(master)$ ecs-preview env ls
prod
test
```

**Comment by iamhopaul123** [comment]
Close this one for now since:

1. we probably don't need to do it for `env ls`
2. for `env delete` I tried to delete the CFN stack then run `env delete`, it was successful.
3. merged in a PR addressing `env init` problem.

Feel free to reopen it if any idempotency issue concerning `env` happens!
