### ISSUE TITLE
Move template rendering logic to a separate package

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#661]
### Ask

The following pattern is repeated across our codebase to render a file that's under the `templates/` directory:
https://github.com/aws/amazon-ecs-cli-v2/blob/f71e1a5d57283f16be059ff3b1a143b744a36876/internal/pkg/cli/pipeline_init.go#L268-L284

We should instead create a separate `template` package to reduce duplication:
```go
package template

type Template struct {
    path string
    data interface{}
    
    box packd.Box
}

// MarshalBinary renders the template and returns its content. 
// This method implements the encoding.BinaryMarshaler interface.
func (t *Template) MarshalBinary() ([]bytes, error) {
   	// do logic above
}
```

Then we can refactor all the duplicated template code to invoke `t.MarshalBinary`

**Comment by kohidave** [comment]
The package name templates might be a little confusing given that this will almost certainly be used with the built in `template` package - but I love the idea!

**Comment by efekarakus** [comment]
Our code shouldn't have to interact with any stdlib pkg like "text/template" or "html/template" anymore, because this "template" package will take on those dependencies.

Given that are we okay with the "template" name or would you like something else?

**Comment by kohidave** [comment]
Sorry - I misunderstood!
