### ISSUE TITLE
Store Pipeline S3 bucket URL in SSM parameters store

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#694]
As described in #649, we will push our addons CFN template to the same bucket that pipeline uses. The bucket is created in our Stackset instance when we do `env init`. So we want to store the URL for the S3 bucket in the SSM parameters store (env variable) so that we can get access to the URL when we deploy addons CFN stack.

**Comment by kohidave** [comment]
Do we still need to do this, given the `getProjectResources` method?
