### ISSUE TITLE
Add clean-up step for e2e test if fails

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#701]
Currently it seems like our e2e test won't automatically clean up resources (e.g., cfn stack) after failure. We should probably let e2e test handle cleaning those resources so that no zombie resources left.

**Comment by kohidave** [comment]
They'll clean up after failures where ginkgo doesn't crash. If ginkgo crashes, we won't clean them up - that's true.

**Comment by efekarakus** [comment]
Resolving no action
