### ISSUE TITLE
"make test" fails with go 1.14

### ISSUE THREAD

**Issue by sonofachamp** [aws/amazon-ecs-cli-v2#778]
`make test` fails with the error message `fatal error: checkptr: unsafe pointer conversion` which appears related to an issue with `packr` and go 1.14. The `-d=checkptr` compile time check is enabled by default as part of go 1.14 on non-Windows platforms. I don't think there's anything we can change, but opened this for tracking purposes until it's fixed.

Related:
https://github.com/gobuffalo/packr/issues/261
https://golang.org/doc/go1.14#compiler

**Comment by efekarakus** [comment]
We should probably look into upgrading to https://github.com/markbates/pkger

**Comment by sonofachamp** [comment]
There's also a proposal to natively support embedding static assets: https://github.com/golang/go/issues/35950, though it seems `pkger` will be more immediately available.
