### ISSUE TITLE
Emoji and Spinner glyphs don't work on Windows

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#79]
Good news is, colors and the prompt work - but the emojis and spinner don't work as well. 
![Screen Shot 2019-09-23 at 7 01 45 PM](https://user-images.githubusercontent.com/828419/65475523-bce06900-de34-11e9-808e-f0c96027728e.png)
![Screen Shot 2019-09-23 at 6 48 14 PM](https://user-images.githubusercontent.com/828419/65475524-bce06900-de34-11e9-9edd-629bce21e039.png)

**Comment by hencrice** [comment]
#180 Removes emoji for Windows so we should be good for now
