### ISSUE TITLE
Make common-used functions more generic

### ISSUE THREAD

**Issue by iamhopaul123** [aws/amazon-ecs-cli-v2#842]
So far  we have functions like `askProject`, `askEnvName` in a lot of our subcommands (`show`, `status` and `logs` for example). We might want to abstract them so that we don't necessarily repeat ourselves by defining them repetitively across the `cli` package, and facilitate testing (so that we can greatly simplify the unit test of most of subcommands in `cli` package).

**Comment by kohidave** [comment]
An idea: https://gist.github.com/kohidave/f8bca96a1c0ca4fef2efeec7002c8f55

**Comment by efekarakus** [comment]
https://github.com/aws/amazon-ecs-cli-v2/pull/888 solves this

**Comment by SoManyHs** [comment]
Closed by #888
