### ISSUE TITLE
No way to set Fargate platform version

### ISSUE THREAD

**Issue by Dids** [aws/amazon-ecs-cli-v2#897]
When using `ecs-cli`, the Fargate platform version seems to always default to `LATEST`, which at the time of writing this is `1.3.0`, eg. the version that doesn't support EFS.

From what I can tell, there's not a single option in the CLI for overriding the platform, so the only CLI-friendly solution would be to use AWS CLI instead, updating the service, right?

**Comment by efekarakus** [comment]
Hi @Dids !

Yes, the ecs-cli-v1 doesn't seem to have a way of setting the platform version:
https://github.com/aws/amazon-ecs-cli/blob/b4be65622ad9faa9e3a073bbae8690ddb88dc435/ecs-cli/modules/cli/compose/entity/service/service.go#L499

Like you suggested the only way to do this right now with a CLI seems to be with the AWS CLI's [create-service](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/create-service.html) command and `--platform-version` flag.
 
I'll close the issue but please feel free to open it if you have more questions!
