### ISSUE TITLE
Implement app init

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#94]
The App commands are not currently super useful, since their main behavior is taken care of by `init`, but once we start implementing `deploy` and `show`, it'll be useful to already have the namespace defined.

This task is for creating an `app init` command that:

1. Checks to see if we're in a WS
2. Prompts the user for the application *type* they want to build
3. Prompts the user for the application Dockerfile (right now - in the future we'll let them select creating a directory with one of our templated directories)
4. Writes the manifest to the workspace root
5. Writes the application into SSM

This task can be broken down into 2 parts:

1. Adding the Application to SSM (we currently only store projects and envs)
2. Wiring up the init command based on the current `ecs init` command

**Comment by efekarakus** [comment]
The work until step 4) is done, step 5) can be picked up after https://github.com/aws/amazon-ecs-cli-v2/pull/225 is merged

**Comment by sonofachamp** [comment]
Looks like #225 is now merged and writing applications to SSM will be required for #230
