### ISSUE TITLE
Default value for networkMode for aws ecs register-task-definition --generate-cli-skeleton

### ISSUE THREAD

**Issue by tkumark** [aws/amazon-ecs-cli-v2#943]
When running aws ecs register-task-definition --generate-cli-skeleton the neworkMode is set to "host". But according to the documention the default network mode is "Bridge" so I think when we run generate-cli-skeleton the value should be populated with "Bridge" instead of "Host"

**Comment by kohidave** [comment]
Hi friend! I think this might better fit in the AWS CLI Repo https://github.com/aws/aws-cli

If that's a better fit, just let me know and I'll close this issue.

**Comment by tkumark** [comment]
its fine close the case
