### ISSUE TITLE
[bug] BackendService port and healthcheck values are overwritten if there are environment overrides

### ISSUE THREAD

**Issue by kohidave** [aws/amazon-ecs-cli-v2#966]
It looks like when we're creating a backend service, if we load the environment overrides: 

https://github.com/aws/amazon-ecs-cli-v2/blob/master/internal/pkg/manifest/backend_svc.go#L112-L119

We will always blindly override the port and command. Since the 0 value of port is actually 0, this means that if there are any overrides, the port will be overwritten to be 0 (which is always wrong).

**Comment by iamhopaul123** [comment]
maybe for a quick fix we can have another `copyAndApply` func for `imageWithPortAndHealthcheck`?
