### ISSUE TITLE
Only accepts dockerfile named Dockerfile 

### ISSUE THREAD

**Issue by Louise15926** [aws/amazon-ecs-cli-v2#979]
## Current Behavior
If I name my dockerfile something other than 'Dockerfile' (say 'db.Dockerfile'), during `app deploy` it will give me this error: _"unable to prepare context: context must be a directory"_. 

```bash
$ ecs-preview app init --dockerfile "db.Dockerfile"
$ ecs-preview app deploy # throws error
```

## Expected Behavior
Not throwing this error

**Comment by iamhopaul123** [comment]
Plus, if dockerfile path is not passed in by a flag then "pb.Dockerfile" cannot be recognized and listed when selecting which dockerfile to use.
