### ISSUE TITLE
Change layout of Additional AWS Resources

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli-v2#994]
As outlined in issue #915, addons templates currently don’t support [Conditions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html).  

For completeness, users can’t write `Description`, `Metadata`, `Mappings`, `Conditions`, and `Transform` sections into their addons template.  
The only supported sections are `Parameters`, `Resources`, and `Outputs`.

## Proposal
We propose changing the `addons/` directory structure to be one CFN template per addon.
For example, if a user wants to add a DDB table and an S3 bucket addon, the file structure will be:
```bash
my-svc/
  manifest.yaml
  addons/
    mytable-ddb.yaml
    mybucket-s3.yaml
```
Where `mytable-ddb.yaml` and `mybucket-s3.yaml` can be full CloudFormation templates.
Behind the scenes, we will merge these two templates into one.

This should allow customers to add all the missing sections, and make it easier to write a new addon on their own.

**Comment by FarmaanElahi** [comment]
@efekarakus Is there any specific reason we are spitting this into multiple file ?

**Comment by efekarakus** [comment]
@FarmaanElahi  They can all be in a single file :) Sorry, that wasn't clear enough from the description. 

We're working on adding a new command `storage init` (https://github.com/aws/amazon-ecs-cli-v2/pull/990#issuecomment-637866124) that will generate CF templates under "addons/" for you. These addon commands will create a separate file each time it's run, so that we don't mess with your existing templates. Afterwards, you can move the contents to a single file if you'd like or split them up it won't matter.
